SELECT * FROM CATEGORIAS;  --*
SELECT * FROM PROVEEDORES; --*
SELECT * FROM PRODUCTOS; --*
SELECT * FROM EMPLEADOS; --*
SELECT * FROM CLIENTES; --*
SELECT * FROM ORDENES; --*
SELECT * FROM DETALLE_ORDENES; --*
SELECT * FROM PAISES; --*
SELECT * FROM REGIONES; --*
SELECT * FROM PROVINCIAS; --*

